name: Build Only - x86 Windows

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install PyQT5
        shell: powershell
        run: |
          choco install qt5 -y --params "/AddToPath"
          pip install pyqt5

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install other Python dependencies
        run: pip install -r src/requirements.txt

      - name: Build the app
        run: |
          pyinstaller --name=musicPlayer --windowed src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: musicPlayer
          path: dist/