name: Build Only - x86 MacOS

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Install dependencies
        run: |
          brew update
          brew install python@3.9
          brew install pyqt@5
          pip3 install pyinstaller
          pip3 install -r src/requirements.txt

      - name: Build the app
        run: |
          pyinstaller --name=musicPlayer --windowed src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: musicPlayer
          path: dist/
          retention-days: 5