name: Build and Deploy - x86

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pyqt5
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Build the app
        run: |
          pyinstaller --name=musicPlayer --windowed src/main.py
          
      - name: Deploy to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}

